---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-svc # Deployment name
  labels:
    app: customer-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-svc
  template:
    metadata:
      labels:
        app: customer-svc
    spec:
      containers:
        - name: customer-svc
          image: "mabalazs86/grpc-customer-svc:0.0.1"
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 50051
              protocol: TCP
          env:
            - name: PROTO_DIR
              value: /home/node/app/dist/proto

---
kind: Service
apiVersion: v1
metadata:
  name: customer-svc
  labels:
    app: customer-svc
spec:
  selector:
    app: customer-svc
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-db # Deployment name
  labels:
    app: customer-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-db
  template:
    metadata:
      labels:
        app: customer-db
    spec:
      containers:
        - name: customer-db
          image: postgres:10.1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: customer
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: "customer-db-pgdata"
      volumes:
        - hostPath:
            path: "/home/docker/pgdata"
          name: customer-db-pgdata

---
kind: Service
apiVersion: v1
metadata:
  name: customer-db
  labels:
    app: customer-db
spec:
  type: ClusterIP
  ports:
    - name: customer-db
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: customer-db
