/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from 'grpc';

export namespace customer {
    export interface CustomersService {
        getCustomerById(data: GetCustomerByIdRequest, metadata?: Metadata): Observable<GetCustomerByIdResponse>;
        getCustomersByIds(data: GetCustomersByIdsRequest, metadata?: Metadata): Observable<GetCustomersByIdsResponse>;
        createCustomer(data: CreateCustomerRequest, metadata?: Metadata): Observable<CreateCustomerResponse>;
    }
    export interface Customer {
        id: number;
        name: string;
    }
    export interface GetCustomerByIdRequest {
        id: number;
    }
    export interface GetCustomerByIdResponse {
        customer: customer.Customer;
    }
    export interface GetCustomersByIdsRequest {
        ids: number[];
    }
    export interface GetCustomersByIdsResponse {
        customers: customer.Customer[];
    }
    export interface CreateCustomerRequest {
        name: string;
    }
    export interface CreateCustomerResponse {
        customer: customer.Customer;
    }
}

