/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Metadata } from 'grpc';

export namespace customer {
    export interface CustomersService {
        findOne(data: CustomerById, metadata?: Metadata): Promise<Customer>;
    }
    export interface CustomerById {
        id?: number;
    }
    export interface Customer {
        id?: number;
        name?: string;
    }
}

