/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Metadata } from 'grpc';

export namespace organization {
    export interface OrganizationesService {
        findOne(data: OrganizationById, metadata?: Metadata): Promise<Organization>;
    }
    export interface OrganizationById {
        id?: number;
    }
    export interface Organization {
        id?: number;
        name?: string;
    }
}

